# Generated by Django 5.0.3 on 2024-03-12 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Место привычки')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время старта привычки')),
                ('action', models.CharField(max_length=120, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='D', verbose_name='Частота')),
                ('tribute', models.CharField(blank=True, max_length=100, null=True, verbose_name='Нграда')),
                ('duration', models.IntegerField(verbose_name='продолжительность')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичность')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
