# Generated by Django 5.0.3 on 2024-03-12 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='habit',
            name='pleasant_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Ссылка на приятную привычку'),
        ),
    ]
